"""
Button extractor - automatically generates assets.py from PNG screenshots.

Usage:
    python -m module.dev_tools.button_extract          # Extract all modules
    python -m module.dev_tools.button_extract --module ui  # Specific module
    
Asset naming convention:
    MY_BUTTON.png          -> Button with area/color from image bbox
    MY_BUTTON.AREA.png     -> Override the area bounding box
    MY_BUTTON.COLOR.png    -> Override the color value
    MY_BUTTON.BUTTON.png   -> Override the click area
    TEMPLATE_MY_TEMPLATE.png -> Template object (not Button)

Output: assets/{module}/assets.py
"""

import os
import sys

import cv2
import numpy as np
from PIL import Image

# Add parent to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

from module.base.utils import load_image, get_color, get_bbox, image_size
from module.util.logger import logger


ASSETS_FOLDER = os.path.join(os.path.dirname(__file__), '..', '..', 'assets')
MODULE_FOLDER = os.path.join(os.path.dirname(__file__), '..')
BUTTON_FILE = 'assets.py'

IMPORT_EXP = [
    'from module.base.button import Button',
    'from module.base.template import Template',
    '',
    '# This file was automatically generated by dev_tools/button_extract.py.',
    "# Don't modify it manually.",
    '',
]

VALID_SERVER = ['default']


class ImageExtractor:
    """Extracts Button definitions from PNG images."""
    
    def __init__(self, module, file):
        self.module = module
        self.name, self.ext = os.path.splitext(file)
        self.area, self.color, self.button, self.file = {}, {}, {}, {}
        for server in VALID_SERVER:
            self.load(server)
    
    def get_file(self, genre='', server='default'):
        """Get the file path for an image variant."""
        for ext in ['.png', '.gif']:
            filename = f'{self.name}.{genre}{ext}' if genre else f'{self.name}{ext}'
            filepath = os.path.join(ASSETS_FOLDER, server, self.module, filename).replace('\\', '/')
            if os.path.exists(filepath):
                return filepath
        
        filename = f'{self.name}.{genre}.png' if genre else f'{self.name}.png'
        return os.path.join(ASSETS_FOLDER, server, self.module, filename).replace('\\', '/')
    
    def extract(self, file):
        """Extract area and color from image."""
        image = load_image(file)
        size = image_size(image)
        if size != (1280, 720):
            logger.warning(f'{file} has non-standard resolution: {size}')
        bbox = get_bbox(image)
        mean = get_color(image=image, area=bbox)
        mean = tuple(np.rint(mean).astype(int))
        return bbox, mean
    
    def load(self, server='default'):
        """Load image data for a server."""
        file = self.get_file(server=server)
        if os.path.exists(file):
            area, color = self.extract(file)
            button = area
            
            # Check for override files
            override = self.get_file('AREA', server=server)
            if os.path.exists(override):
                area, _ = self.extract(override)
            
            override = self.get_file('COLOR', server=server)
            if os.path.exists(override):
                _, color = self.extract(override)
            
            override = self.get_file('BUTTON', server=server)
            if os.path.exists(override):
                button, _ = self.extract(override)
            
            self.area[server] = area
            self.color[server] = color
            self.button[server] = button
            self.file[server] = file
        else:
            logger.warning(f'{self.name} not found for server {server}, using default')
            self.area[server] = self.area.get('default', (0, 0, 0, 0))
            self.color[server] = self.color.get('default', (0, 0, 0))
            self.button[server] = self.button.get('default', (0, 0, 0, 0))
            self.file[server] = self.file.get('default', '')
    
    @property
    def expression(self):
        return f'{self.name} = Button(area={self.area}, color={self.color}, button={self.button}, file={self.file})'


class TemplateExtractor:
    """Extracts Template definitions from PNG images."""
    
    def __init__(self, module, file):
        self.module = module
        self.name, self.ext = os.path.splitext(file)
        self.file = {}
        for server in VALID_SERVER:
            self.load(server)
    
    def get_file(self, server='default'):
        for ext in ['.png', '.gif']:
            filepath = os.path.join(ASSETS_FOLDER, server, self.module, f'{self.name}{ext}').replace('\\', '/')
            if os.path.exists(filepath):
                return filepath
        return os.path.join(ASSETS_FOLDER, server, self.module, f'{self.name}.png').replace('\\', '/')
    
    def load(self, server='default'):
        file = self.get_file(server)
        if os.path.exists(file):
            self.file[server] = file
        else:
            self.file[server] = self.file.get('default', '')
    
    @property
    def expression(self):
        return f'{self.name} = Template(file={self.file})'


class ModuleExtractor:
    """Extracts all assets from a module directory."""
    
    def __init__(self, name):
        self.name = name
        self.folder = os.path.join(ASSETS_FOLDER, 'default', name)
    
    @staticmethod
    def split(file):
        name, ext = os.path.splitext(file)
        name, sub = os.path.splitext(name)
        return name, sub, ext
    
    def is_base_image(self, file):
        _, sub, _ = self.split(file)
        return sub == ''
    
    @property
    def expression(self):
        exp = []
        if not os.path.exists(self.folder):
            logger.warning(f'Folder not found: {self.folder}')
            return IMPORT_EXP.copy()
        
        for file in sorted(os.listdir(self.folder)):
            if file[0].isdigit():
                continue
            if file.startswith('TEMPLATE_'):
                exp.append(TemplateExtractor(module=self.name, file=file).expression)
                continue
            if self.is_base_image(file):
                exp.append(ImageExtractor(module=self.name, file=file).expression)
                continue
        
        logger.info(f'Module: {self.name} ({len(exp)} assets)')
        result = IMPORT_EXP + exp
        return result
    
    def write(self):
        """Write assets.py to the module folder."""
        module_path = os.path.join(MODULE_FOLDER, self.name)
        os.makedirs(module_path, exist_ok=True)
        
        filepath = os.path.join(module_path, BUTTON_FILE)
        with open(filepath, 'w', newline='') as f:
            for text in self.expression:
                f.write(text + '\n')
        
        logger.info(f'Written: {filepath}')


def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(description='Extract button definitions from PNG assets')
    parser.add_argument('--module', help='Specific module to extract (e.g., ui, campaign)')
    parser.add_argument('--all', action='store_true', help='Extract all modules')
    args = parser.parse_args()
    
    if args.module:
        # Extract single module
        extractor = ModuleExtractor(args.module)
        extractor.write()
        print(f'Extracted: {args.module}')
    else:
        # Extract all modules
        default_dir = os.path.join(ASSETS_FOLDER, 'default')
        if not os.path.exists(default_dir):
            print(f'No assets directory found at: {default_dir}')
            print('Create an assets/default/<module>/ directory with PNG files.')
            return
        
        for module_name in sorted(os.listdir(default_dir)):
            module_path = os.path.join(default_dir, module_name)
            if os.path.isdir(module_path):
                extractor = ModuleExtractor(module_name)
                extractor.write()
        
        print('\nDone! All assets extracted.')


if __name__ == '__main__':
    main()
