import datetime

# This file was automatically generated by al/config/config_generator.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    DefaultTask_Device_Platform = 'PC'  # PC, Emulator
    DefaultTask_Device_EmulatorSerial = '127.0.0.1:7555'
    DefaultTask_Device_ScreenshotMethod = 'WindowsGraphics'  # WindowsGraphics, BitBlt, ADB, scrcpy, nemu_ipc
    DefaultTask_Device_ControlMethod = 'PostMessage'  # PostMessage, PyDirectInput, ADB, minitouch, maatouch, nemu_ipc
    DefaultTask_Ocr_Engine = 'default'  # default, cnocr, paddle, rapid, dgocr, onnx
    DefaultTask_Ocr_TargetHeight = 0
    DefaultTask_Window_Title = ''
    DefaultTask_Window_Class = ''
    DefaultTask_Window_Exe = ''
    DefaultTask_NTEKeyBinding_SkillKey = 'e'
    DefaultTask_NTEKeyBinding_UltimateKey = 'q'
    DefaultTask_NTEKeyBinding_ArcKey = 'r'
    DefaultTask_NTEKeyBinding_DodgeKey = 'shift'
    DefaultTask_NTEKeyBinding_InteractKey = 'f'
    DefaultTask_Restart_SchedulerWatcher_Enable = False  # True, False
    DefaultTask_Restart_SchedulerWatcher_TimeDelta = 10
    DefaultTask_Restart_SchedulerWatcher_WarningCount = 3
    DefaultTask_Restart_GameRestart_FatalErrorRestart = False  # True, False
    DefaultTask_Restart_GameRestart_MaxRetryTimes = 20
    DefaultTask_Restart_CloseTask_Enable = False  # True, False
    DefaultTask_Restart_CloseTask_MaxErrorOccur = 2
    DefaultTask_Restart_InstanceRestart_Enable = False  # True, False
    DefaultTask_Restart_InstanceRestart_MaxRetryTimes = 20
    DefaultTask_Storage_Storage = {}
    DefaultTask_Scheduler_Command = 'DefaultTask'
    Daily_Scheduler_Enable = False  # True, False
    Daily_Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    Daily_Scheduler_Command = 'Daily'
    Daily_Scheduler_SuccessInterval = 0
    Daily_Scheduler_FailureInterval = 120
    Daily_Scheduler_ServerUpdate = '00:00'
    Daily_NTEDaily_EnableDaily = True  # True, False
    Daily_NTEDaily_CollectMail = True  # True, False
    Daily_NTEDaily_CollectBattlepass = True  # True, False
    Daily_NTEDaily_CollectActivity = True  # True, False
    Daily_Storage_Storage = {}
    Fishing_Scheduler_Enable = False  # True, False
    Fishing_Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    Fishing_Scheduler_Command = 'Fishing'
    Fishing_Scheduler_SuccessInterval = 0
    Fishing_Scheduler_FailureInterval = 120
    Fishing_Scheduler_ServerUpdate = '00:00'
    Fishing_NTEFishing_EnableFishing = False  # True, False
    Fishing_NTEFishing_SellFish = True  # True, False
    Fishing_NTEFishing_BaitRestock = True  # True, False
    Fishing_NTEFishing_FishingMode = 'normal'  # normal, aggressive, manual
    Fishing_Storage_Storage = {}
    Anomaly_Scheduler_Enable = False  # True, False
    Anomaly_Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    Anomaly_Scheduler_Command = 'Anomaly'
    Anomaly_Scheduler_SuccessInterval = 0
    Anomaly_Scheduler_FailureInterval = 120
    Anomaly_Scheduler_ServerUpdate = '00:00'
    Anomaly_NTEAnomaly_EnableAnomaly = False  # True, False
    Anomaly_NTEAnomaly_AnomalyType = 'all'  # all, normal, hard, weekly
    Anomaly_NTEAnomaly_AnomalyCount = 3
    Anomaly_Storage_Storage = {}
    Rhythm_Scheduler_Enable = False  # True, False
    Rhythm_Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    Rhythm_Scheduler_Command = 'Rhythm'
    Rhythm_Scheduler_SuccessInterval = 0
    Rhythm_Scheduler_FailureInterval = 120
    Rhythm_Scheduler_ServerUpdate = '00:00'
    Rhythm_NTERhythm_EnableRhythm = False  # True, False
    Rhythm_NTERhythm_RhythmDifficulty = 'normal'  # normal, hard, expert
    Rhythm_Storage_Storage = {}
    Heist_Scheduler_Enable = False  # True, False
    Heist_Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    Heist_Scheduler_Command = 'Heist'
    Heist_Scheduler_SuccessInterval = 0
    Heist_Scheduler_FailureInterval = 120
    Heist_Scheduler_ServerUpdate = '00:00'
    Heist_NTEHeist_EnableHeist = False  # True, False
    Heist_NTEHeist_HeistKeyInterval = 0.05
    Heist_Storage_Storage = {}
    AutoCombat_Scheduler_Enable = False  # True, False
    AutoCombat_Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    AutoCombat_Scheduler_Command = 'AutoCombat'
    AutoCombat_Scheduler_SuccessInterval = 0
    AutoCombat_Scheduler_FailureInterval = 120
    AutoCombat_Scheduler_ServerUpdate = '00:00'
    AutoCombat_NTECombat_EnableCombat = True  # True, False
    AutoCombat_NTECombat_AutoDodge = True  # True, False
    AutoCombat_NTECombat_AutoCounter = True  # True, False
    AutoCombat_NTECombat_CombatMode = 'auto'  # auto, manual, semi
    AutoCombat_Storage_Storage = {}
    SkipDialog_Scheduler_Enable = False  # True, False
    SkipDialog_Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    SkipDialog_Scheduler_Command = 'SkipDialog'
    SkipDialog_Scheduler_SuccessInterval = 0
    SkipDialog_Scheduler_FailureInterval = 120
    SkipDialog_Scheduler_ServerUpdate = '00:00'
    SkipDialog_NTEDialog_EnableSkipDialog = True  # True, False
    SkipDialog_NTEDialog_DialogSpeed = 'fast'  # fast, normal
    SkipDialog_Storage_Storage = {}
    FastTravel_Scheduler_Enable = False  # True, False
    FastTravel_Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    FastTravel_Scheduler_Command = 'FastTravel'
    FastTravel_Scheduler_SuccessInterval = 0
    FastTravel_Scheduler_FailureInterval = 120
    FastTravel_Scheduler_ServerUpdate = '00:00'
    FastTravel_NTETravel_EnableFastTravel = True  # True, False
    FastTravel_NTETravel_TravelMethod = 'auto'  # auto, map, quest
    FastTravel_Storage_Storage = {}