import datetime

# This file was automatically generated by al/config/config_generator.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    DefaultTask_Scheduler_Enable = False  # True, False
    DefaultTask_Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    DefaultTask_Scheduler_Command = 'DefaultTask'
    DefaultTask_Scheduler_SuccessInterval = 0
    DefaultTask_Scheduler_FailureInterval = 120
    DefaultTask_Device_Platform = 'auto'  # auto, pc, adb
    DefaultTask_Device_Serial = 'auto'
    DefaultTask_Device_ScreenshotMethod = 'auto'  # auto, ADB, WindowsGraphics, BitBlt, scrcpy, nemu_ipc
    DefaultTask_Device_ControlMethod = 'auto'  # auto, ADB, PostMessage, PyDirectInput, minitouch, maatouch
    DefaultTask_Ocr_Engine = 'default'  # default, cnocr, paddle, rapid, dgocr, onnx
    DefaultTask_Ocr_TargetHeight = 0
    DefaultTask_Window_Title = ''
    DefaultTask_Window_Class = ''
    DefaultTask_Window_Exe = ''
    DefaultTask_Storage_Storage = {}